version: '3'
services:

  server-prod:
    build:
      context: ./server

    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db-prod
    volumes:
      - ./var/www/html:/var/www/html
      - ./server:/server
      - /server/node_modules

  db-prod:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=snake_eater
    ports:
      - "5432:5432"

volumes:
  server-dev:
